services:
  hytale:
    build: .
    container_name: hytale
    restart: unless-stopped
    volumes:
      - ./hytale-server:/hytale-server
    ports:
      - 5520:5520/udp
    stdin_open: true
    tty: true
